### ISSUE TITLE
Cannot read properties of undefined (reading 'replace') error on "Joining as DM"

### ISSUE THREAD

**Issue by martintoreilly** [cyruzzo/AboveVTT#2382]
Hi. I'm following the instructions in the error message to create an issue here.

I got the error message shown below today when attempting to restart a game after a break of quite a few months, using the "Join as DM" AboveVTT button on the D&D Beyond campaign page. In the meantime, one of my players has deleted two of the characters from their D&D Beyond account, without them being removed from the campaign in D&D Beyond. However, I can still see the tokens for these characters on the map, which I can still access after closing the error message and clicking on the map tab (the two deleted characters are the "east" and "west" characters of the diamond of 4 characters in the Stonehill Inn on the map. However, none of the tokens, for the deleted or still existing characters or NPCs can be interacted with. I wonder if perhaps these deleted characters still exist in the AboveVTT data and the error occurs when trying to access the now deleted underlying D&D Beyind character data?

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/b98dbcb1-8945-4ab4-9eff-f8e1db095686">

Martin

**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/fdbdbb38-35c2-4e25-a823-2c9b7d71e46c?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-14T17:50:38.949Z
      TOKEN IS CACHED

LOG 2024-08-14T17:50:38.940Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T17:50:38.934Z
      build_journal

LOG 2024-08-14T17:50:38.925Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T17:50:38.925Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T17:50:38.925Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T17:50:38.924Z
      monster_search_filters
      {}

LOG 2024-08-14T17:50:38.924Z
      init_scenes_panel

LOG 2024-08-14T17:50:38.921Z
      TOKEN IS CACHED

LOG 2024-08-14T17:50:38.917Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T17:50:38.917Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T17:50:38.917Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T17:50:38.917Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T17:50:38.917Z
      migrate_token_customizations has already completed

LOG 2024-08-14T17:50:38.916Z
      init_tokens_panel

LOG 2024-08-14T17:50:38.915Z
      init_sidebar_tabs

LOG 2024-08-14T17:50:38.858Z
      init_ui

LOG 2024-08-14T17:50:38.855Z
      startup_step Setting up UI

LOG 2024-08-14T17:
```

**Comment by Azmoria** [comment]
Tokens exist in our data so what you described is probably correct.

The error is due to a change ddb made breaking the loading. We are looking for something that is undefined because of it.

You should be able to ignore it for the most part and click close - you'll probably have to reselect a current scene.

I believe this is fixed in beta now, have to do some testing to see if anything else was afffected.

**Comment by martintoreilly** [comment]
Thanks. The situation is as you described - I can clear the error screen by pressing the escape key and I do need to select a current scene each time. The non-interacting tokens appears to have been transitory as I've been able to select these after relaunching AboveVTT with the "Join as DM" button. I've now deleted the tokens for the deleted players and still get the error, so I think I'm only experiencing the behaviour you expect caused by the ddb breaking change. If you are tracking this elsewhere then please do close this issue.
